# generated by cursor

import os
import argparse

import torch.distributed as dist


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dist-backend", type=str, default="gloo")
    parser.add_argument("--init_method", type=str, default="tcp://127.0.0.1:29540")
    args = parser.parse_args()

    rank = int(os.environ["RANK"])
    world_size = int(os.environ["WORLD_SIZE"])

    print(f"rank={rank} world_size={world_size} init_method={args.init_method}", flush=True)
    dist.init_process_group(
        backend=args.dist_backend,
        init_method=args.init_method,
        world_size=world_size,
        rank=rank,
    )
    print(f"rank={rank} process group ready", flush=True)
    dist.destroy_process_group()


if __name__ == "__main__":
    main()

