# generated by cursor

import os


def main():
    keys = [
        "RANK",
        "LOCAL_RANK",
        "WORLD_SIZE",
        "MASTER_ADDR",
        "MASTER_PORT",
        "SLURM_LOCALID",
        "SLURM_NODEID",
    ]
    for k in keys:
        print(f"{k}={os.environ.get(k)}")


if __name__ == "__main__":
    main()

