# generated by cursor
import os
from pathlib import Path

import numpy as np
import pandas as pd
import harmonypy as hm


def load_npy(path: Path) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(str(path))
    return np.load(path)


def main():
    base_dir = Path(__file__).resolve().parent
    mtx_base = base_dir / "GSE240429_data" / "data" / "filtered_expression_matrices"

    slices = [1, 2, 3, 4]
    data_sizes = [2378, 2349, 2277, 2265]

    mats = []
    for s in slices:
        p = mtx_base / str(s) / "hvg_matrix.npy"
        mats.append(load_npy(p))  # expected: genes x cells

    genes = mats[0].shape[0]
    if any(m.shape[0] != genes for m in mats):
        raise ValueError(f"Unexpected gene dim among hvg matrices: {[m.shape for m in mats]}")

    # Concatenate as genes x total_cells (features x samples)
    d = np.concatenate(mats, axis=1)
    if d.shape != (genes, sum(data_sizes)):
        print("Warning: concatenated shape mismatch:", d.shape, "expected", (genes, sum(data_sizes)))

    # batch labels for harmonypy meta_data
    batch_labels = np.concatenate(
        (
            np.zeros(data_sizes[0]),
            np.ones(data_sizes[1]),
            np.ones(data_sizes[2]) * 2,
            np.ones(data_sizes[3]) * 3,
        )
    ).astype(str)
    df = pd.DataFrame(batch_labels, columns=["dataset"])

    print("Running harmony on matrix:", d.shape, "cells_total=", len(df))
    harmony = hm.run_harmony(d, meta_data=df, vars_use=["dataset"])
    Z = harmony.Z_corr

    # harmonypy may return either (genes x cells) or (cells x genes)
    if Z.shape[0] == genes:
        genes_x_cells = Z
    elif Z.shape[1] == genes:
        genes_x_cells = Z.T
    else:
        raise ValueError(f"Unexpected harmony.Z_corr shape: {Z.shape}, genes={genes}")

    print("harmony.Z_corr converted shape (genes x cells):", genes_x_cells.shape)

    # Split along cell axis
    start = 0
    for i, s in enumerate(slices):
        n = data_sizes[i]
        part = genes_x_cells[:, start : start + n]  # gene x cell
        start += n
        out = mtx_base / str(s) / "harmony_matrix.npy"
        np.save(out, part)
        print("saved", out, "shape", part.shape)


if __name__ == "__main__":
    main()

